# Generated by Django 3.1.5 on 2021-01-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial_manual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Minigame',
            new_name='Gamemode',
        ),
    ]
